DROP TABLE IF EXISTS posts;
	DROP TYPE IF EXISTS imgext;
	DROP TYPE IF EXISTS rating;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS users;
	DROP TYPE IF EXISTS perms;

DROP EXTENSION IF EXISTS tag_parser CASCADE;
